# Generated by Django 4.2.5 on 2023-10-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_item_image_item_local_image_item_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
